version: '3'
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: digitalocean.com/php
        container_name: test-app
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./backend:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: test-webserver
        tty: true
        ports:
            - "801:80"
            - "4431:443"
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:8
        container_name: test-db
        tty: true
        ports:
            - "33061:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: taskmanager
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./data/mysql:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    #PhpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: test-phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_HOST=db
            - UPLOAD_LIMIT=1024M
        depends_on:
            - db
        links:
            - db
        ports:
            - "8088:80"
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
